import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

const COLORS = {
    // Material Design 3 Palette (M3)
    PRIMARY: [103, 80, 164], // M3 Baseline Primary (#6750A4)
    SECONDARY: [98, 91, 113], // M3 Secondary (#625B71)
    SURFACE: [254, 247, 255], // M3 Surface (#FEF7FF)
    SURFACE_CONTAINER: [243, 237, 247], // M3 Surface Container (#F3EDF7)
    TEXT_MAIN: [29, 27, 32], // M3 On Surface (#1D1B20)
    TEXT_MUTED: [73, 69, 79], // M3 On Surface Variant (#49454F)
    BG_LIGHT: [247, 242, 250], // M3 Surface Container Low
    SEVERITY: {
        critical: [179, 38, 30], // M3 Error (#B3261E)
        high: [234, 88, 12],
        medium: [202, 138, 4],
        low: [37, 99, 235],
        info: [98, 91, 113],
    }
};

export const exportScanToPDF = (scanData: any) => {
    try {
        const { source, stats, findings, timestamp, id } = scanData;
        console.log('Generating Modern PDF for:', source.name);

        const doc = new jsPDF();
        const pageWidth = doc.internal.pageSize.getWidth();
        const pageHeight = doc.internal.pageSize.getHeight();

        // --- 1. COVER PAGE ---
        // Header Decoration
        doc.setFillColor(COLORS.SECONDARY[0], COLORS.SECONDARY[1], COLORS.SECONDARY[2]);
        doc.rect(0, 0, pageWidth, 120, 'F');

        // Logo / App Name
        doc.setTextColor(255, 255, 255);
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(28);
        doc.text('SCA REPORT', 20, 50);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(14);
        doc.text('Security Analysis & Vulnerability Report', 20, 62);

        // Project Name
        doc.setTextColor(255, 255, 255);
        doc.setFontSize(48);
        doc.setFont('helvetica', 'bold');
        const projectName = source.name.toUpperCase();
        const splitProjectName = doc.splitTextToSize(projectName, pageWidth - 40);
        doc.text(splitProjectName, 20, 85);

        // Metadata Box (Material Design Card)
        doc.setFillColor(COLORS.SURFACE_CONTAINER[0], COLORS.SURFACE_CONTAINER[1], COLORS.SURFACE_CONTAINER[2]);
        doc.roundedRect(20, 140, pageWidth - 40, 65, 4, 4, 'F');

        doc.setTextColor(COLORS.PRIMARY[0], COLORS.PRIMARY[1], COLORS.PRIMARY[2]);
        doc.setFontSize(11);
        doc.setFont('helvetica', 'bold');
        doc.text('SCAN INFORMATION', 30, 155);

        doc.setTextColor(COLORS.TEXT_MAIN[0], COLORS.TEXT_MAIN[1], COLORS.TEXT_MAIN[2]);
        doc.setFont('helvetica', 'normal');
        doc.text(`Scan ID:`, 30, 165);
        doc.text(`${id}`, 70, 165);
        doc.text(`Date:`, 30, 172);
        doc.text(`${new Date(timestamp).toLocaleString()}`, 70, 172);
        doc.text(`Source:`, 30, 179);
        doc.text(`${source.type.toUpperCase()}`, 70, 179);
        doc.text(`Files:`, 30, 186);
        doc.text(`${stats.filesScanned || 0} files scanned`, 70, 186);

        // Footer Branding
        doc.setTextColor(COLORS.TEXT_MUTED[0], COLORS.TEXT_MUTED[1], COLORS.TEXT_MUTED[2]);
        doc.setFontSize(12);
        doc.text('Generated by Antigravity SCA System', pageWidth / 2, pageHeight - 20, { align: 'center' });

        // --- 2. TABLE OF CONTENTS ---
        doc.addPage();
        drawHeader(doc, 'Table of Contents');

        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(COLORS.TEXT_MAIN[0], COLORS.TEXT_MAIN[1], COLORS.TEXT_MAIN[2]);
        doc.text('1. Executive Summary', 20, 45);
        doc.text('2. Vulnerability Distribution', 20, 55);
        doc.text('3. Detailed Findings', 20, 65);

        const severities = ['critical', 'high', 'medium', 'low', 'info'];
        let tocY = 75;
        severities.forEach((sev) => {
            const count = findings.filter((f: any) => f.severity === sev).length;
            if (count > 0) {
                doc.setFontSize(11);
                doc.setFont('helvetica', 'normal');
                doc.setTextColor(COLORS.PRIMARY[0], COLORS.PRIMARY[1], COLORS.PRIMARY[2]);
                doc.text(`- ${sev.toUpperCase()} Findings (${count})`, 30, tocY);
                tocY += 8;
            }
        });

        // --- 3. EXECUTIVE SUMMARY ---
        doc.addPage();
        drawHeader(doc, 'Executive Summary');

        autoTable(doc, {
            startY: 40,
            head: [['Project Metric', 'Value']],
            body: [
                ['Project Name', source.name],
                ['Scan Date', new Date(timestamp).toLocaleString()],
                ['Scan ID', id],
                ['Total Files Scanned', stats.filesScanned],
                ['Total Lines Scanned', stats.linesScanned || 'N/A'],
                ['Scan Duration', `${stats.duration}s`],
                ['Total Vulnerabilities', findings.length],
            ],
            theme: 'striped',
            headStyles: { fillColor: COLORS.PRIMARY as [number, number, number] },
        });

        const summaryFinalY = (doc as any).lastAutoTable.finalY + 15;

        const barChartY = (doc as any).lastAutoTable.finalY + 15;
        doc.setFontSize(12);
        doc.text('Visual Severity Distribution', 15, barChartY);

        let barOffset = 0;
        const totalW = pageWidth - 30;
        const totalFindings = findings.length || 1;

        severities.forEach(sev => {
            const count = stats.findings[sev] || 0;
            const barW = (count / totalFindings) * totalW;
            if (barW > 0) {
                const color = COLORS.SEVERITY[sev as keyof typeof COLORS.SEVERITY];
                doc.setFillColor(color[0], color[1], color[2]);
                doc.rect(15 + barOffset, barChartY + 5, barW, 6, 'F');
                barOffset += barW;
            }
        });

        // Distribution Table
        const distTableY = barChartY + 20;
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.setTextColor(COLORS.TEXT_MAIN[0], COLORS.TEXT_MAIN[1], COLORS.TEXT_MAIN[2]);
        doc.text('Vulnerability Distribution', 15, distTableY);

        autoTable(doc, {
            startY: distTableY + 5,
            head: [['Severity', 'Count', 'Percentage', 'Recommendation']],
            body: severities.map(sev => {
                const count = stats.findings[sev] || 0;
                const percentage = findings.length > 0 ? ((count / findings.length) * 100).toFixed(1) : 0;
                const rec = sev === 'critical' ? 'IMMEDIATE FIX' :
                    sev === 'high' ? 'Priority Fix' :
                        sev === 'medium' ? 'Schedule Fix' : 'Monitor';
                return [sev.toUpperCase(), count, `${percentage}%`, rec];
            }),
            theme: 'grid',
            headStyles: { fillColor: COLORS.SECONDARY as [number, number, number] },
            columnStyles: {
                1: { halign: 'center' },
                2: { halign: 'center' }
            },
            didParseCell: (data) => {
                if (data.section === 'body' && data.column.index === 0) {
                    const sev = data.cell.raw?.toString().toLowerCase();
                    if (sev && COLORS.SEVERITY[sev as keyof typeof COLORS.SEVERITY]) {
                        data.cell.styles.textColor = COLORS.SEVERITY[sev as keyof typeof COLORS.SEVERITY] as [number, number, number];
                        data.cell.styles.fontStyle = 'bold';
                    }
                }
            }
        });

        // Top Vulnerable Files
        const fileCounts = findings.reduce((acc: any, f: any) => {
            acc[f.file] = (acc[f.file] || 0) + 1;
            return acc;
        }, {});
        const topFiles = Object.entries(fileCounts)
            .sort((a: any, b: any) => b[1] - a[1])
            .slice(0, 5);

        if (topFiles.length > 0) {
            const topFilesY = (doc as any).lastAutoTable.finalY + 15;
            doc.text('Top Vulnerable Files', 15, topFilesY);
            autoTable(doc, {
                startY: topFilesY + 5,
                head: [['File Path', 'Issue Count']],
                body: topFiles as any,
                theme: 'striped',
                headStyles: { fillColor: [100, 116, 139] as [number, number, number] },
            });
        }

        // --- 4. DETAILED FINDINGS ---
        const severityPageMap: Record<string, number> = {};

        // Group findings by severity
        const groupedBySeverity = findings.reduce((acc: any, f: any) => {
            if (!acc[f.severity]) acc[f.severity] = [];
            acc[f.severity].push(f);
            return acc;
        }, {});

        severities.forEach(sev => {
            const sevFindings = groupedBySeverity[sev];
            if (!sevFindings || sevFindings.length === 0) return;

            doc.addPage();
            severityPageMap[sev] = (doc as any).internal.getNumberOfPages();
            drawHeader(doc, `Detailed Findings: ${sev.toUpperCase()}`);

            let currentY = 40;

            // Group by Title (Error Name) within Severity
            const groupedByTitle = sevFindings.reduce((acc: any, f: any) => {
                if (!acc[f.title]) acc[f.title] = [];
                acc[f.title].push(f);
                return acc;
            }, {});

            Object.entries(groupedByTitle).forEach(([title, issues]: [string, any]) => {
                if (currentY > 240) {
                    doc.addPage();
                    drawHeader(doc, `Detailed Findings: ${sev.toUpperCase()} (cont.)`);
                    currentY = 40;
                }

                // Title Banner - Material Design Chip/Bar style
                doc.setFillColor(COLORS.SURFACE_CONTAINER[0], COLORS.SURFACE_CONTAINER[1], COLORS.SURFACE_CONTAINER[2]);
                doc.roundedRect(15, currentY, pageWidth - 30, 10, 5, 5, 'F');

                doc.setTextColor(COLORS.TEXT_MAIN[0], COLORS.TEXT_MAIN[1], COLORS.TEXT_MAIN[2]);
                doc.setFontSize(11);
                doc.setFont('helvetica', 'bold');
                doc.text(title, 22, currentY + 6.5);
                currentY += 15;

                issues.forEach((issue: any) => {
                    const messageLines = doc.splitTextToSize(issue.message, pageWidth - 45);
                    const neededHeight = 10 + (messageLines.length * 4) + (issue.code ? 35 : 0);

                    if (currentY + neededHeight > 270) {
                        doc.addPage();
                        drawHeader(doc, `Detailed Findings: ${sev.toUpperCase()} (cont.)`);
                        currentY = 40;
                    }

                    // Metadata - Stacked to avoid overlap with long file paths
                    doc.setFontSize(7);
                    doc.setTextColor(COLORS.TEXT_MUTED[0], COLORS.TEXT_MUTED[1], COLORS.TEXT_MUTED[2]);
                    doc.setFont('helvetica', 'normal');
                    doc.text(`CATEGORY: ${issue.category.toUpperCase()}`, 20, currentY);
                    currentY += 4;

                    doc.setFontSize(8);
                    doc.setFont('helvetica', 'bold');
                    doc.setTextColor(COLORS.PRIMARY[0], COLORS.PRIMARY[1], COLORS.PRIMARY[2]);
                    const fileText = `FILE: ${issue.file}:${issue.line}`;
                    const splitFile = doc.splitTextToSize(fileText, pageWidth - 40);
                    doc.text(splitFile, 20, currentY);

                    const fileLinesHeight = (Array.isArray(splitFile) ? splitFile.length : 1) * 3.5;
                    currentY += fileLinesHeight + 2;

                    // Message
                    doc.setFontSize(9);
                    doc.setTextColor(COLORS.TEXT_MAIN[0], COLORS.TEXT_MAIN[1], COLORS.TEXT_MAIN[2]);
                    doc.text(messageLines, 20, currentY);
                    currentY += (messageLines.length * 4) + 4;

                    // Code snippets - Clean Material Design 3 style
                    if (issue.code) {
                        // Sanitize string to prevent jspdf rendering bugs with weird characters
                        const safeCode = (issue.code || '').replace(/\r/g, '').replace(/[^\x20-\x7E\n\r\t\u00A0-\u01FF]/g, ' ');
                        const rawCode = safeCode.length > 2000 ? safeCode.substring(0, 2000) + '... (truncated)' : safeCode;

                        const lines = rawCode.split('\n').slice(0, 10);
                        const wrappedLines = doc.splitTextToSize(lines.join('\n'), pageWidth - 55);
                        const finalLines = wrappedLines.slice(0, 15);

                        const lineHeight = 4;
                        const boxHeight = (finalLines.length * lineHeight) + 6;

                        if (currentY + boxHeight > 275) {
                            doc.addPage();
                            drawHeader(doc, `Detailed Findings: ${sev.toUpperCase()} (cont.)`);
                            currentY = 40;
                        }

                        // Background Box - Neutral Light Grey for better readability
                        doc.setFillColor(245, 247, 250);
                        doc.roundedRect(20, currentY, pageWidth - 40, boxHeight, 2, 2, 'F');

                        // Vertical Accent (Primary Color)
                        doc.setFillColor(COLORS.PRIMARY[0], COLORS.PRIMARY[1], COLORS.PRIMARY[2]);
                        doc.rect(20, currentY, 1.5, boxHeight, 'F');

                        // Code Text - Use standard Helvetica with explicit spacing reset
                        doc.setFont('helvetica', 'normal');
                        doc.setFontSize(7.5);
                        doc.setTextColor(51, 65, 85); // Slate-700
                        doc.setCharSpace(0); // Reset character spacing

                        // Render lines individually to ensure perfect control and avoid jspdf rendering glitches
                        finalLines.forEach((line: string, idx: number) => {
                            doc.text(line, 25, currentY + 6 + (idx * 4));
                        });

                        currentY += boxHeight + 10;
                    } else {
                        currentY += 8;
                    }
                });
            });
        });

        // Add retroactive links to TOC
        doc.setPage(2);
        let linkY = 75;
        severities.forEach(sev => {
            if (severityPageMap[sev]) {
                doc.setTextColor(COLORS.PRIMARY[0], COLORS.PRIMARY[1], COLORS.PRIMARY[2]);
                doc.text(`[Page ${severityPageMap[sev]}]`, 180, linkY, { align: 'right' });
                doc.link(30, linkY - 5, 160, 7, { url: `#page=${severityPageMap[sev]}` });
                linkY += 8;
            }
        });

        // --- FOOTERS & PAGE NUMBERS ---
        const pageCount = (doc as any).internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);

            // Footer Line
            doc.setDrawColor(226, 232, 240);
            doc.line(15, pageHeight - 15, pageWidth - 15, pageHeight - 15);

            doc.setFontSize(8);
            doc.setTextColor(COLORS.TEXT_MUTED[0], COLORS.TEXT_MUTED[1], COLORS.TEXT_MUTED[2]);
            doc.setFont('helvetica', 'normal');
            doc.text(`${source.name} | Security Scan Report`, 15, pageHeight - 10);
            doc.text(`Page ${i} of ${pageCount}`, pageWidth - 15, pageHeight - 10, { align: 'right' });
        }

        // Save
        const filename = `${source.name.replace(/[^a-z0-9]/gi, '_').toLowerCase()}_security_report.pdf`;
        doc.save(filename);

    } catch (err) {
        console.error('Modern PDF Generation Error:', err);
        alert('Failed to generate modern PDF report.');
    }
}

function drawHeader(doc: jsPDF, title: string) {
    const pageWidth = doc.internal.pageSize.getWidth();

    // Header Bar
    doc.setFillColor(COLORS.PRIMARY[0], COLORS.PRIMARY[1], COLORS.PRIMARY[2]);
    doc.rect(0, 0, pageWidth, 25, 'F');

    // Header Title
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(title, 15, 17);

    // Logo text
    doc.setFontSize(10);
    doc.text('ANTIGRAVITY SCA', pageWidth - 15, 17, { align: 'right' });
}
