"""Add phase 5.3 fields

Revision ID: 93d88eec46b1
Revises: 7560d2e01a4c
Create Date: 2026-07-31 07:02:27.061281+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93d88eec46b1'
down_revision: Union[str, None] = '7560d2e01a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('findings', sa.Column('status', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_findings_status'), 'findings', ['status'], unique=False)
    op.add_column('projects', sa.Column('cron_schedule', sa.String(length=100), nullable=True))
    op.add_column('projects', sa.Column('enabled_scanners', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'enabled_scanners')
    op.drop_column('projects', 'cron_schedule')
    op.drop_index(op.f('ix_findings_status'), table_name='findings')
    op.drop_column('findings', 'status')
    # ### end Alembic commands ###
