import { NextRequest, NextResponse } from 'next/server';
import { sendPdfToTelegram } from '@/lib/telegram';
import { generateScanPdfBuffer } from '@/lib/pdf-export';
import { getScanById } from '@/lib/db-helpers';

export async function POST(request: NextRequest) {
    try {
        const body = await request.json();
        const { scanId } = body;

        if (!scanId) {
            return NextResponse.json(
                { error: 'Scan ID is required' },
                { status: 400 }
            );
        }

        // Load scan data from database
        const scanData = await getScanById(scanId);

        if (!scanData) {
            return NextResponse.json(
                { error: 'Scan not found' },
                { status: 404 }
            );
        }

        // Transform scan data to match PDF export format
        const pdfData = {
            id: scanData.id,
            timestamp: scanData.timestamp,
            source: {
                name: scanData.source?.name || 'Unknown Project',
                type: scanData.source?.type || 'local',
            },
            stats: {
                filesScanned: scanData.stats?.filesScanned || 0,
                linesScanned: scanData.stats?.linesScanned || 'N/A',
                duration: scanData.stats?.duration || 0,
                findings: scanData.stats?.findings || {
                    critical: 0,
                    high: 0,
                    medium: 0,
                    low: 0,
                    info: 0,
                },
            },
            findings: (scanData.findings || []).map((f: any) => ({
                severity: f.severity || 'info',
                title: f.title || 'Unknown',
                message: f.message || '',
                category: f.category || 'Security',
                file: f.file || '',
                line: f.line || 0,
                code: f.code || '',
            })),
        };

        // Generate PDF buffer
        const pdfResult = generateScanPdfBuffer(pdfData);

        if (!pdfResult) {
            return NextResponse.json(
                { error: 'Failed to generate PDF' },
                { status: 500 }
            );
        }

        const { buffer, filename } = pdfResult;

        // Create caption for Telegram
        const totalFindings = pdfData.findings.length;
        const critical = pdfData.stats.findings.critical || 0;
        const high = pdfData.stats.findings.high || 0;
        const medium = pdfData.stats.findings.medium || 0;

        const caption = `
🔒 <b>Security Scan Report</b>

📁 Project: <b>${pdfData.source.name}</b>
📅 Date: ${new Date(pdfData.timestamp).toLocaleString()}
📊 Total Findings: <b>${totalFindings}</b>

⚠️ Critical: ${critical}
🔴 High: ${high}
🟡 Medium: ${medium}

Generated by SCA Platform
    `.trim();

        // Create or reuse a topic for this report
        const { getOrCreateForumTopic } = await import('@/lib/telegram');
        let messageThreadId: number | undefined;

        console.log(`[Manual Send] Getting or creating Telegram topic for: ${pdfData.source.name}...`);
        const topicResult = await getOrCreateForumTopic(pdfData.source.name);

        if (topicResult.success) {
            messageThreadId = topicResult.message_thread_id;
            console.log(`[Manual Send] Topic ID: ${messageThreadId}`);
        } else {
            console.warn('[Manual Send] Could not get/create Telegram topic:', topicResult.error);
        }

        // Send to Telegram
        const result = await sendPdfToTelegram(buffer, filename, caption, messageThreadId);

        if (!result.success) {
            return NextResponse.json(
                { error: result.error || 'Failed to send to Telegram' },
                { status: 500 }
            );
        }

        return NextResponse.json({ success: true });
    } catch (error) {
        console.error('Send to Telegram error:', error);
        return NextResponse.json(
            { error: 'Internal server error' },
            { status: 500 }
        );
    }
}
